@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor 用户
participant 前端
participant 后端
database 数据库

用户 -> 前端 : 请求进入新建字典界面
前端 -> 后端 : /builtdictionary/builtdictionarysave
后端 -> 数据库 : builtdictionarysave()
前端 <-- 数据库 : response
@enduml

1.用户进入新建字典界面
2.前端向后端请求/builtdictionary/builtdictionarysave，参数：字典名称，字典类型，字典选择，字典键数据，字典值数据
3.后端调用builtdictionarysave(),将字典名称，字典类型，字典选择，字典键数据，字典值数据保存到数据库
4.后端返回保存成功到前端。
