@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor 用户
participant 前端
participant 后端
database 数据库

用户 -> 前端 : 请求进入添加关联界面
前端 -> 后端 : /datarelate/datarelateadd
后端 -> 数据库 : datarelateadd()
前端 <-- 数据库 : response
@enduml

1.用户进入添加关联界面
2.前端向后端请求/datarelate/datarelateadd，参数：关联名称，关联类型，关联主表，主表关联字段，关联从表，从表关联字段，是否关联删除，是否左连接
3.后端调用datarelateadd(),将关联名称，关联类型，关联主表，主表关联字段，关联从表，从表关联字段，是否关联删除，是否左连接保存到数据库
4.后端返回保存成功到前端。
