@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor 用户
participant 前端
participant 后端
database 数据库

用户 -> 前端 : 请求进入表单编辑界面
前端 -> 后端 : /page/pageload
后端 -> 数据库 : pageload()
前端 <-- 数据库 : response
@enduml

1.用户点击对应的菜单链接，弹出发起页面
2.前端向后端请求/page/pageload，参数：页面id，版本号(发起页面，版本号为空)
3.后端调用pageload(),通过页面id去获取之前配置好的大JSON,版本号（发起页面，取最新的版本号）返给前端
4.后端返回数据到前端。

