@startuml
'https://plantuml.com/sequence-diagram
title 新建流程分类
actor 管理员
participant 前端
participant 后端
database 数据库
autonumber

管理员 -> 前端: 点击删除
activate 前端
前端 -> 后端: /flow/flowCategory/delete
activate 后端
后端 -> 数据库: getById()
activate 数据库
alt 判断根据id得到的流程分类为空
后端 --[#blue]> 前端: response
end
后端 -> 数据库: getListByFilter()
alt 判断得到的流程设计集合不为空
后端 --[#blue]> 前端: response
end
后端 -> 数据库: remove()
数据库 --[#blue]> 前端: response
@enduml
1.用户发起删除流程分类请求
2.前端向后端请求/flow/flowCategory/delete，参数：流程分类id（不为空）
3.后端调用getById()，查询表zz_flow_category数据，参数：流程分类id
4.后端向前端返回当前流程分类不存在
5.后端调用getListByFilter()，查询表zz_flow_entry，参数：流程设计表实体(设置流程分类id)
6.后端向前端返回当前流程分类已存在关联流程设计，流程分类不能修改
7.后端调用remove()，删除表zz_flow_category数据，参数：流程分类id
8.后端向前端返回删除结果