@startuml
'https://plantuml.com/sequence-diagram
title 新建流程分类
actor 管理员
participant 前端
participant 后端
database 数据库
autonumber

管理员 -> 前端: 点击新建，进入新建流程分类页面
activate 前端
前端 -> 后端: /flow/flowCategory/add
activate 后端
后端 -> 数据库: has()
activate 数据库
alt 流程分类数量大于0
后端 --[#blue]> 前端: response
end
后端 -> 数据库: add()
数据库 --[#blue]> 前端: response
@enduml
1.用户发起新建流程分类请求
2.前端向后端请求/flow/flowCategory/add，参数：流程分类名称（不为空）、流程分类编码（不为空）
3.后端调用has()，查询表zz_flow_category是否有值，参数：流程分类名称、流程分类编码
4.后端向前端返回流程分类已存在
5.后端调用add()，添加数据到表zz_flow_category，参数：流程分类id、流程分类名称、流程分类编码、
创建时间、创建人、更新时间、更新人
6.后端向前端返回添加结果
