@startuml
'https://plantuml.com/sequence-diagram
title 流程分类下拉列表
actor 管理员
participant 前端
participant 后端
database 数据库
autonumber

管理员 -> 前端: 选择流程分类下拉
activate 前端
前端 -> 后端: /flow/flowCategory/listDict
activate 后端
后端 -> 数据库: getFlowCategoryList()
activate 数据库
数据库 --[#blue]> 前端: response
@enduml
1.用户发起流程分类下拉列表请求
2.前端向后端请求/flow/flowCategory/listDict
3.后端调用getListByFilter()，查询表zz_flow_category数据
4.后端向前端返回流程分类下拉列表数据
